MCLF/mclf

mclf/semistable_reduction/superp.py

so it builds against on readthedocs.org

Make Python3 compliant

---

Dockerfile
README.md
example.ipynb

so people can try MCLF without going to the hassle of installing Sage 8.2

Enable binder configuration

---

mclf/berkovich/affinoid_domain.py
mclf/berkovich/berkovich_line.py
mclf/berkovich/berkovich_trees.py
mclf/berkovich/type_V_points.py
mclf/curves/morphisms_of_smooth_projective_curves.py
mclf/padic_extensions/fake_padic_completions.py
mclf/padic_extensions/weak_padic_galois_extensions.py
mclf/semistable_reduction/reduction_trees.py
mclf/semistable_reduction/superp.py

@swewers when you create a Pull Request into the main repository, Circle CI automatically runs the doctests for you.

Fix doctests

---

.circleci/config.yml
docs/conf.py
docs/index.rst
docs/readthedocs.yml
mclf/__init__.py
mclf/berkovich/affinoid_domain.py
mclf/berkovich/berkovich_line.py
mclf/berkovich/berkovich_trees.py
mclf/monkey.py
mclf/semistable_reduction/reduction_trees.py

and turn warnings into errors. Gives problems such as #14 more visibility.
Fixes #14.

Fix docbuild & check whether documentation builds

---

.circleci/config.yml
docs/.gitignore
docs/morphisms_of_smooth_projective_curves
mclf/semistable_reduction/admissible_reduction.py

Fix imports to fix docbuild on readthedocs.org

---

docs/admissible_reduction.rst
docs/affinoid_domain.rst
docs/berkovich_line.rst
docs/berkovich_trees.rst
docs/fake_padic_completions.rst
docs/fake_padic_extensions.rst
docs/morphisms_of_smooth_projective_curves.rst
docs/reduction_trees.rst
docs/smooth_projective_curves.rst
docs/superell.rst
docs/superp.rst
docs/type_V_points.rst
docs/weak_padic_galois_extensions.rst

it does not help much if these links point to the trivial rst documents.

Fix Edit On Github links on readthedocs

---

README.md

mostly so I can easily play with it by clicking a link on our home page. But I
think it's also nice for visitors to our page to see that there is some more
experimental stuff.

Make the develop branch more accessible

---

.circleci/config.yml
.circleci/coverage.sitecustomize.py
.coveragerc
README.md

Produce coverage reports with coverage/coveralls

---

.circleci/config.yml

thanks to @NathanDunfield for figuring out what had broken pip

Fix coverage tests

---

mclf/semistable_reduction/reduction_trees.py

The changes are in `ReductionTree.conductor_exponent`
and in `InertialComponent.conductor_exponent`
ToDo:
- write better documentation
- use caching for `outdegree`

`conductor_exponent` now works in all cases

---

mclf/benchmarks/semistable.py

the case reported in #61. Fixes #61.

Add a test case/benchmark

---

mclf/2018-01-07-164705.term
mclf/curves/smooth_projective_curves.py
mclf/semistable_reduction/semistable_models.py

Some small changes to `curves`:
- new option `check` in SmoothProjectiveCurves
- a divisor on a curve is just a list of points

Oberwolfach

---

mclf/semistable_reduction/semistable_models.py

The method ``base_field`` of 
``SemistableModel`` should be called
``constant_base_field``

Fix issue #70

---

mclf/curves/smooth_projective_curves.py

There was an error in the code computing the degree of the field of
constants of a curve. I fixed that and wrote
a doctest with the example that triggered
the error.

fix field_of_constants_degree

---

mclf/monkey/__init__.py
mclf/monkey/trac_26066.py

Monkey patch mac_lane_step bug

---

mclf/berkovich/berkovich_line.py

using Sage objects as default parameters breaks the docbuild of that method @swewers

Fix docbuild on rtd

---

mclf/curves/morphisms_of_smooth_projective_curves.py
mclf/curves/smooth_projective_curves.py
mclf/semistable_reduction/reduction_trees.py
mclf/semistable_reduction/semistable_models.py

This tries to fix the problems 
described in issue #103.
The code is very experimental..

WIP: attempt to fix a bug

---

mclf/berkovich/berkovich_trees.py

- a Berkovich tree now has an attribute
`_attr` which is initialized as an empty
dictionary. It is never use by this
module, and may be used by applications
to store arbitrary information related to
a vertex
- fixed bug: `T.children()` now returns a
*copy* of the internal list of children.
To change the tree structure, one has to
change `T._children`
- fixed bug: `find_point` now works for
empty tree
- new function `remove_point`
- more examples
- fixed some typos

improved version of `berkovic_trees`

---

mclf/berkovich/berkovich_line.py

- new function `point_from_valuation` for class `BerkovichLine`
- new function `valuation` for class
`TypeIPointOnBerkovichLine`

valuations corresponding to points of type I

---

mclf/curves/smooth_projective_curves.py

Implement several improvements of `smooth_projective_curves`
- implemented a method to determine a prime of good reduction, for curves over number fields
- implemented reduction to a good prime
- for curves over number fields, the genus is computed, by default, via reduction to some good prime
- one can also define a curve by a polynomial in two variables
- several other small improvements and bug fixes

Improve curves

---

docs/admissible_reduction.rst
docs/affinoid_domain.rst
docs/berkovich_trees.rst
docs/fake_padic_completions.rst
docs/fake_padic_embeddings.rst
docs/fake_padic_extensions.rst
docs/morphisms_of_smooth_projective_curves.rst
docs/piecewise_affine_functions.rst
docs/reduction_trees.rst
docs/semistable_models.rst
docs/smooth_projective_curves.rst
docs/superelliptic_curves.rst
docs/superp_models.rst
docs/type_V_points.rst
docs/weak_padic_galois_extensions.rst

I added a 'members' directive to all files; in some environements this 
is necessary to document the complete code.

Fix the documentation

---

mclf/curves/smooth_projective_curves.py

I ran all doctests, it seems to be fine.

Proposed fix for Issue #124

---

mclf/benchmarks/semistable.py
mclf/berkovich/affinoid_domain.py
mclf/berkovich/berkovich_line.py
mclf/berkovich/berkovich_path.py
mclf/berkovich/berkovich_path_old.py
mclf/berkovich/berkovich_trees.py
mclf/berkovich/piecewise_affine_functions.py
mclf/curves/morphisms_of_smooth_projective_curves.py
mclf/curves/picard_curves.py
mclf/curves/smooth_projective_curves.py
mclf/curves/superelliptic_curves.py
mclf/monkey/trac_24533.py
mclf/monkey/trac_25294.py
mclf/monkey/trac_25360.py
mclf/monkey/trac_25440.py
mclf/monkey/trac_25441.py
mclf/monkey/trac_26066.py
mclf/monkey/util.py
mclf/padic_extensions/elements_of_fake_padic_completion.py
mclf/padic_extensions/fake_padic_completions.py
mclf/padic_extensions/fake_padic_embeddings.py
mclf/padic_extensions/fake_padic_extensions.py
mclf/padic_extensions/slope_factors.py
mclf/padic_extensions/weak_padic_galois_extensions.py
mclf/semistable_reduction/admissible_reduction.py
mclf/semistable_reduction/reduction_trees.py
mclf/semistable_reduction/semistable_models.py

This is cleaning more code formatting, according to pycodestyle warnings.
The next step would be to correct suggestions by the `ruff` linter.

full-scale pep8 cleanup

---

mclf/semistable_reduction/reduction_trees.py

- typo in documentations fixed
- broken long lines
- unused variable

some trivial improvements to reduction_trees
